export default [
  {
    label: "العربية",
    i18n: "ar"
  }, {
    label: "Български",
    i18n: "bg"
  }, {
    label: "中文(简体)",
    i18n: "zh"
  }, {
    label: "České",
    i18n: "cs"
  }, {
    label: "Deutsch",
    i18n: "de"
  }, {
    label: "English",
    i18n: "en"
  }, {
    label: "Ελληνικά",
    i18n: "el"
  }, {
    label: "Español",
    i18n: "es"
  }, {
    label: "Français",
    i18n: "fr"
  }, {
    label: "עברית",
    i18n: "he"
  }, {
    label: "Hrvatski",
    i18n: "hr"
  }, {
    label: "မြန်မာဘာသာ",
    i18n: "my"
  }, {
    label: "Italiano",
    i18n: "it"
  }, {
    label: "Nederlands",
    i18n: "nl"
  }, {
    label: "Norsk bokmål",
    i18n: "nb"
  }, {
    label: "Polski",
    i18n: "pl"
  }, {
    label: "Português",
    i18n: "pt"
  }, {
    label: "Русский",
    i18n: "ru"
  }, {
    label: "Română",
    i18n: "ro"
  }, {
    label: "Slovenščina",
    i18n: "sl"
  }, {
    label: "Svenska",
    i18n: "sv"
  }, {
    label: "Türkçe",
    i18n: "tr"
  }, {
    label: "tiếng Việt",
    i18n: "vi"
  }
];
